### ISSUE TITLE
Move mobilecommons interface into its own library

### ISSUE THREAD

**Issue by jonuy** [DoSomething/gambit#12]
And add back into this project through the `package.json`

**Comment by aaronschachter** [comment]
Adding a note that we're including the [npm mobilecommons library](https://github.com/DoSomething/gambit/blob/713e57ad23ea82a7551b6688fec2986c4751084a/package.json#L19) but don't seem to use it at all in our [`mobilecommons.js`](https://github.com/DoSomething/gambit/blob/1.1.0/mobilecommons/mobilecommons.js).

**Comment by aaronschachter** [comment]
Once #706 is in, we're only using the `profile_update` endpoint. This might come in handy for Quicksilver / Messaging Groups API projects but not necessary for this one -- labelling as NO
