### ISSUE TITLE
Include Source Detail in Northstar + Rogue requests

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#170]
Both Northstar and Rogue accept a `source_detail` parameter we're not sending anything for.

* [ ] User
* Sounds like we should be sending a keyword, if sent? https://dosomething.slack.com/archives/C2C8NLNAY/p1507925259000068

* [ ] Signup
* [ ] Post:

* Ideas for sending various details: `keyword-mirror`, `keyword-menu`, `broadcast-59cad9d9b76942000496f4df`. If we went this route, it'd make sense to send a detail with `keyword-` prefix to our User source detail

cc @jamjensen @justkika @sheyd

**Comment by sheyd** [comment]
@aaronschachter I like the initial thoughts. I think it's at least parity with what we have now from MoCo. I'll let @jamjensen add if he has any thoughts on if more details are required, or has any syntactical preferences. Otherwise, I think 👍  on this and it addresses our current needs.

**Comment by aaronschachter** [comment]
@jamjensen @sheyd -- Confirming we're 👍  to change the prefix a Northstar User's `source_detail` with the `keyword-`? e.g. `keyword-mirror` instead of `mirror`

**Comment by jamjensen** [comment]
@aaronschachter yes, this looks good to me. Will `source-detail` be limited to keyword info, or will it also include, `broadcast-number`?

**Comment by DFurnes** [comment]
It might be nice to mirror the source details we've been [saving from Mobile Commons](https://github.com/DoSomething/northstar-mobilecommonsd/blob/a56b366339713d370dc13948f2fe9deb87d9559f/app/Jobs/SendUserToNorthstar.php#L98-L112), so `keyword/mirror` or `broadcast/1234`. (Especially if we decide to standardize all SMS sources as a single `sms` in the future!)

**Comment by aaronschachter** [comment]
That's the ticket @DFurnes 💸  

If there's a Broadcast ID set in the request, we can pass it for User source @jamjensen. In theory, I don't think we'd ever create a User via Gambit when a member is responding to a broadcast -- they should be in Customer.io / Northstar already?

**Comment by jamjensen** [comment]
@aaronschachter agreed, that member should be in C.io / Northstar already.

I was referring to the `source_detail` as it relates to the signup. If Gambit is posting the signup to Rogue, can it also pass along `source_detail` if the signup comes from a broadcast or keyword?

**Comment by aaronschachter** [comment]
Yup! The's the second part of this issue. What should we send for `source_detail` when a User signs up for a random Campaign they get pitched when sending a MENU keyword?

**Comment by jamjensen** [comment]
@aaronschachter I would say the keyword that they text to signup for the campaign after receiving the MENU message.

**Comment by jamjensen** [comment]
One question on gambit status in Northstar -- If the gambit statuses are active, less, inactive, undeliverable - does that mean that "active" does not only mean subscribed but also engaged? If that's true then why don't we call the status "engaged" and have less be "listening"?

**Comment by aaronschachter** [comment]
Active only means subscribed. We're sending a Last Messaged At date to help segmenting for who's engaged.

For the MENU keyword - they don't get prompted to text a keyword back, it's a YES / NO response (feel free to try it out on staging 😉 !)

**Comment by jamjensen** [comment]
Ah so LESS doesn't contain all the members that are "listening" - just the ones that have asked to receive less messaging. +1 to the Last Messaged At date. Will that also be on their Northstar profile? 

I did go through the MENU flow on staging -- so I should rephrase, can we send the keyword that is associated with the campaign they're signing up for? For example, let's take the campaign Defend Dreamers which has DREAM as it's keyword. If I were to signup by just texting the keyword, the `signup_source_detail` should be `keyword/DREAM`. And if I were to signup by responding to the MENU message, the `signup_source_detail` would be `menu/DREAM`.  Thoughts? Are we saying the same thing?

**Comment by aaronschachter** [comment]
> Will that also be on their Northstar profile?

Yep!
> `keyword/DREAM`

What about simply storing `menu` as the detail, without the keyword? Some Campaigns get multiple keywords, we'd be arbitrarily picking one.

**Comment by jamjensen** [comment]
Sweet! Not currently seeing `last_messaged_at` in aurora. Is there an ETA on when that will be complete? 

Yeah, sounds good. We want to know how they signed up, and storing `menu` as the detail accomplishes that.

**Comment by DFurnes** [comment]
@jamjensen Yeah, I need to add that in. It is currently stored in Northstar, just not displayed.
