### ISSUE TITLE
Make updating a member to `undeliverable` on failed messages configurable

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#333]
_FEATURE OVERVIEW_
-------------------
#### User Story

As an DS Engineer, I want to be able to "turn off" the updating of users `sms_status` to `undeliverable` when Blink relays message error delivery metadata to Gambit Conversations. So that, under certain circumstances, the error delivery metadata requests are allowed to update the messages in G-Conversations, without updating the member `sms_status` property.

#### Why This Matters
We run the risk that, in the case there is an editorial, setup, or misc error in the broadcast. Twilio will reject all the messages in a synchronous way. This situation would set a potentially massive amount of users in an undeliverable status.

#### Current Workaround w/o Feature (if applicable)
1. Pause the `twilio-sms-outbound-error-relay` queue worker. Once paused, purge the messages in the queue.
2. Run a script to update all the `queued` messages and manually set them to `failed`.

**Comment by aaronschachter** [comment]
Related to https://www.pivotaltracker.com/story/show/158156103 for image size validation via Contentful UI (we should still add a check to avoid Twilio errors for attachment size)
