### ISSUE TITLE
When the outbound message fails to be delivered. The user's state should not change.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#337]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a DS member, when an outbound message fails to be delivered to my handset, my conversation's state should remain the same as my last successful interaction. Otherwise, the response I would get the next time I interact with the chatbot would be confusing to me.

#### Why This Matters
I could be in the middle of a reportback flow and be thrown out of the flow by a failed broadcast without me knowing why/what's going on.

**Comment by rapala61** [comment]
We spoke about this issue in Story Time on June 6th. Some things to consider:

- We change the user's state before asserting that the message was successfully delivered.
- We have discussed the concept of a creating "draft" that get's "saved" once we get confirmation from Twilio that the message was delivered. This is an interesting paradigm that I like so far, but does introduce another layer of complexity.

**Comment by aaronschachter** [comment]
One idea I've been mulling over is instead of checking properties on the Conversation model, checking the topic/campaign/template of its last outbound message. If the message was failed, skip back to the last delivered message to figure out how to reply.
