### ISSUE TITLE
Setup endpoints to stress test application 

### ISSUE THREAD

**Issue by jonuy** [DoSomething/gambit#338]
- [x] A basic GET endpoint to respond with a simple response. This shouldn't try to access anything from the database, just field and return a response. Something like this can help determine if there's any difference in the environments the app is hosted in (heroku, nodejitsu, rpc, etc)
- [x] A POST endpoint to execute some query on our backend. The intent here is to simulate more closely the state of the app when it's hit with concurrent queries that require retrieving/creating/updating data from the database.

**Comment by aaronschachter** [comment]
We've got POST endpoints that query the DB, so that covers the 2nd task. This issue doesn't entail actually writing any stress tests, so sweet -- it's done!
