### ISSUE TITLE
add mock objects for API calls in unit tests

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/gambit#456]
We can simulate API calls with mock objects instead of checking for the test env variable and skipping the API call. We can still use emitted events in our tests, because of our code's async nature. 

http://sinonjs.org/
https://facebook.github.io/jest/

**Comment by tongxiang** [comment]
for calls to things like: 

1. dosomething API
2. bitly API

**Comment by aaronschachter** [comment]
This issue for tests we've since deleted can be closed in favor of #671 too.  

We used Nock in Phoenix JS (https://github.com/DoSomething/phoenix-js/pull/12) and it seemed to work well, something to consider @deadlybutter .

**Comment by deadlybutter** [comment]
From my limited reading Nock seems great for testing an API wrapper like PhoenixJS, but it doesn't seem very thorough for an entire app like Gambit. I'll most likely go with Mocha as that's generally well accepted/used
