### ISSUE TITLE
Better handling of DS Content API authentication

### ISSUE THREAD

**Issue by jonuy** [DoSomething/gambit#462]
The app never logs out, so we could cause flooding issues on the Drupal API side. A couple things we should do:
- [ ] Create a new DS account that this app specifically uses to auth against the API
- [ ] Implement a system to cache session information between app runs
- [ ] Implement a system to logout where it makes sense

**Comment by aaronschachter** [comment]
Chatted with @DFurnes about this and we think we're ok to close this out.

Once we remove the legacy endpoint (#706), Gambit will only authenticate to Phoenix only to post Reportbacks and Signups. Once https://github.com/DoSomething/northstar/issues/429 is in, we'd be in a place to use Northstar for posting Signups/Reportbacks and would no longer need to authenticate to Phoenix at all -- the information we get from the Phoenix Campaigns doesn't require authentication.
