### ISSUE TITLE
Better handling of unfinished reportbacks

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/gambit#463]
When a user starts a reportback and is unable to finish it for some reason (MC error, user error, any number of reasons), the created reportback doc isn't removed from the database. 

The next time the user attempts to reportback again for the same campaign, their submitted reportback data ends up in the previously created reportback doc.

**Comment by aaronschachter** [comment]
Linking to #529 and #506, possibly related adventures in SMS reportbacks.

**Comment by aaronschachter** [comment]
Haven't seen an overwrite, but just a failed submission overall per #506. Closing as this work against this will be opened against #506

**Comment by aaronschachter** [comment]
Opening this back up as a todo for #506 to track work for building out support for unfinished reportbacks, e.g. "Hey looks like you were almost finished - we just need to know how many nouns you verbed"

**Comment by aaronschachter** [comment]
Completed with launch of new `chatbot` endpoint.
