### ISSUE TITLE
Add to the list of "yes" options in MCRouting.yesNoGateway

### ISSUE THREAD

**Issue by jonuy** [DoSomething/gambit#513]
#### The scenario

In some SMS flows we ask the users a yes/no question and route them to a Mobile Commons opt-in path based on their answer. One case in particular where this issue was seen is when we ask if users can send photos with their phone (ie - do they have a plan that supports sending MMS). We process `y`, `yes`, `ya`, and `yea` as affirmative responses. We'll want to also add to that list:

- `yeah`
- `yup`
- `yas`
- `of course`

#### The fix

The simplest solution is probably to just update the array in code where these strings are set: 
https://github.com/DoSomething/ds-mdata-responder/blob/dev/app/lib/ds-routing/controllers/MCRouting.js#L38

@blisteringherb This might be a good one to sink your teeth into. The code itself is really really trivial, but it'll allow you to go through the process of setting up your environment, running tests, committing and deploying.

cc: @tongxiang

**Comment by tongxiang** [comment]
:disappointed: the torch has been passed

**Comment by aaronschachter** [comment]
It looks like the DRY way to implement the fix where would be to call the [smsHelpers. isYesResponse](https://github.com/DoSomething/ds-mdata-responder/blob/adc78d4d86c4a5db51ad859876c329cd8a656909/app/lib/smsHelpers.js#L72) function when [performing the check for a "Yes"](https://github.com/DoSomething/ds-mdata-responder/blob/adc78d4d86c4a5db51ad859876c329cd8a656909/app/lib/ds-routing/controllers/MCRouting.js#L40)?

**Comment by aaronschachter** [comment]
We've made a request to Mobile Commons to add ["of course" ](https://dosomething.slack.com/archives/mobilecommons/p1468966042000031) to their list, updated description to make same change on ours. I also think we should add YAS
