### ISSUE TITLE
Fix NewRelic monitoring

### ISSUE THREAD

**Issue by jonuy** [DoSomething/gambit#518]
*Updated 8/8*
* [x] Get error logging working

*Updated 7/19 -- next steps per https://github.com/DoSomething/ds-mdata-responder/issues/518#issuecomment-233766089*
* [x] Remove the New Relic add-on
* [x] Remove the custom NR code (require('newrelic');)
* [x] Verify we have no more NR-related log activity
* [x] Re-introduce the newer NR package in code

*Original description*

I'm not sure when it stopped, but it seems like we're no longer getting any reporting to our NewRelic account from this app.

Initially thought that it may be because `require('newrelic')` isn't the first line in [server.js](https://github.com/DoSomething/ds-mdata-responder/blob/dev/server.js#L8) like the NewRelic docs ask for it to be. But that change was done in late 2014 and I'm _pretty_ sure we didn't just go through the entirety of 2015 without getting any NewRelic reporting.

**Comment by aaronschachter** [comment]
The [logs on production](https://dashboard.heroku.com/apps/ds-mdata-responder/logs) are flooded with New Relic related messages, making it really hard to spot any other errors.

> 2016-07-18T15:09:19.214273+00:00 app[web.1]: {"v":0,"level":10,"name":"newrelic","hostname":"9e24e984-e7c8-4f7b-8cc5-f72b27e63081","pid":14,"time":"2016-07-18T15:09:19.213Z","msg":"Not creating segment \"timers.setTimeout\" because no transaction was active","component":"tracer"}
2016-07-18T15:09:29.528610+00:00 app[web.2]: {"v":0,"level":10,"name":"newrelic","hostname":"eb8c319a-467a-4c85-b398-8c01785579b4","pid":14,"time":"2016-07-18T15:09:29.528Z","msg":"Not tracing MongoDB unknown._executeQueryCommand(); no New Relic transaction.","component":"mongodb"}
2016-07-18T15:09:29.528973+00:00 app[web.2]: {"v":0,"level":10,"name":"newrelic","hostname":"eb8c319a-467a-4c85-b398-8c01785579b4","pid":14,"time":"2016-07-18T15:09:29.528Z","msg":"Not tracing MongoDB unknown._executeQueryCommand(); no New Relic transaction.","component":"mongodb"}

cc @blisteringherb

**Comment by aaronschachter** [comment]
Similar errors reported in [this thread](https://discuss.newrelic.com/t/newrelic-shows-no-data-together-with-nodejs/33716/6). New Relic suggests:
> the original forum poster's application did not handle web requests. If an application does not handle web requests (e.g. it only takes care of some background process) you may need to use [custom instrumentation](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/nodejs-custom-instrumentation) for data to appear in New Relic.

**Comment by mshmsh5000** [comment]
It looks as though we have two New Relic integrations in the production Heroku app.

There’s the integration in code, which loads the library and reads the env vars set in Heroku, and then there’s the generic add-on.

The integration in code would be the one generating error messages, and the one that should be reporting into our main New Relic account.

The other one is happily reporting to the auto-created New Relic account we were looking at.

**Comment by aaronschachter** [comment]
There's this message in the New Relic dashboard:
> There are both old and new time metrics for this time window. The response time is accurate, but if you use asynchronous code the stacked bars may not be. To fix this, [upgrade all of your agents to versions that support the new time metrics](https://docs.newrelic.com/docs/data-analysis/user-interface-functions/view-your-data/response-time).

Per that link -- our app should be running NewRelic 1.25 or higher, our package.json currently is set to [1.11.5](https://github.com/DoSomething/ds-mdata-responder/blob/adc78d4d86c4a5db51ad859876c329cd8a656909/package.json#L19).

**Comment by mshmsh5000** [comment]
My suggestion is 

1. Remove the New Relic add-on
2. Remove the custom NR code (`require('newrelic');`)
3. Verify we have no more NR-related log activity
4. Re-introduce the newer NR package in code

**Comment by aaronschachter** [comment]
Thanks @mshmsh5000, I'll give it a shot. I did just try updating package.json to [1.28.3](https://www.npmjs.com/package/newrelic) and restarting but still get the error. 
````
2:11:19 PM web.1 |  {"v":0,"level":10,"name":"newrelic","hostname":"Aarons-MacBook-Pro-2.local","pid":1029,"time":"2016-07-19T21:11:19.284Z","msg":"Not creating segment \"timers.setTimeout\" because no transaction was active","component":"tracer"}
````

Will try from scratch per the steps in your suggestion.

**Comment by aaronschachter** [comment]
Deployed 1.0.1 to production, which has stopped all of the New Relic noise in the logs.

@mshmsh5000  - It also looks like our Heroku add-on New Relic activity has stopped too, although I haven't disabled the Heroku add-on through the UI, so that's a little unexpected (I think?). The transactions stop right around the time of deploy:

<img width="825" alt="screen shot 2016-07-20 at 12 21 47 pm" src="https://cloud.githubusercontent.com/assets/1236811/16999791/a95db5ac-4e74-11e6-931b-4e54ecbcdb27.png">

@mshmsh5000 Confirming our next step should be to disable the add-on within the Heroku UI (step 1) to complete step 3?

**Comment by mshmsh5000** [comment]
Well now! Does that mean that the Heroku add-on doesn't work without the Heroku lib loaded in the app code?

**Comment by aaronschachter** [comment]
@mshmsh5000 Do you mean it won't work without the New Relic (not Heroku) lib loaded?

I've done [a little reading](https://docs.newrelic.com/docs/agents/nodejs-agent/hosting-services/nodejs-agent-heroku) that would have been a little more useful to look at yesterday -- the answer sure looks likes YES, we need to add the `newrelic` package -- see step 7. I'll work on adding back in locally to try pinpoint where the noise is coming from..

**Comment by aaronschachter** [comment]
This add-on seems to be logging activity but not errors.

Our implementation is using the Wayne add-on for $0.00/month. I'm seeing some 401's from Mobile Commons that are nowhere to be found in the New Relic add-on's interface in the "Errors" page. When I navigate to "Error analytics" it urges to upgrade.

Refs #562 
cc @blisteringherb 



<img width="1218" alt="screen shot 2016-08-08 at 9 34 01 am" src="https://cloud.githubusercontent.com/assets/1236811/17487934/e0630fc6-5d4b-11e6-8b35-746e95e4d64b.png">

**Comment by aaronschachter** [comment]
I've changed our production key to post to our main New Relic account to an app named `Gambit` instead of `ds-mdata-responder-heroku`, and I've turned off reporting locally and on staging by setting config variable `NEW_RELIC_ENABLED=false`.

Will give a day or two to 👀 but we should be in a good place to disable the Heroku New Relic add-on completely.
cc @blisteringherb @sheyd

**Comment by aaronschachter** [comment]
I'm seeing some 403's in our New Relic around the time of yesterday's [deployment](https://github.com/DoSomething/gambit/releases/tag/2.0.0) adding checks for `x-gambit-api-key`, so I think it's safe to close out the last remaining todo for this.

<img width="865" alt="screen shot 2016-08-23 at 9 33 57 am" src="https://cloud.githubusercontent.com/assets/1236811/17900883/f265c756-6915-11e6-9b71-74a3038e2739.png">

When I've tested with 404 errors, they didn't appear - but that's by default (per New Relic support in our Heroku ticket). 

For application errors, we can add our own custom events if we want them to appear in new Relic... further progress can be tracked in #562

Related reading:
* https://discuss.newrelic.com/t/process-crashing-errors-are-not-being-reported/27765
* https://discuss.newrelic.com/t/how-to-get-notified-about-error-events/31312/4
* http://stackoverflow.com/questions/26964009/detecting-process-crashes-with-new-relic-in-nodejs
