### ISSUE TITLE
Audit live Opt-in paths for missing mData's

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#546]
This won't be closed with code changes, but opening this issue to track adding the relevant Reportback mData to the Optin Paths configuration like "Invalid Quantity" . Refs scenario 2 in https://github.com/DoSomething/ds-mdata-responder/issues/506#issuecomment-236208672

I've only spot checked a few "Invalid Quantity" OIP's, but we'll want to check on all of the various OIP's that respond back to invalid data being sent.

## todo
* [ ] MMS not received
* [ ] Invalid quantity

### no mData set:
<img width="537" alt="screen shot 2016-08-02 at 2 28 48 pm" src="https://cloud.githubusercontent.com/assets/1236811/17345968/7d3d6064-58bd-11e6-8cb6-3337a673d6b1.png">

### mData set:
<img width="551" alt="screen shot 2016-08-02 at 2 27 49 pm" src="https://cloud.githubusercontent.com/assets/1236811/17345945/6178b3ec-58bd-11e6-97c1-ead689edc59d.png">

cc @classicfreddie @jamjensen

**Comment by aaronschachter** [comment]
@classicfreddie We'll want to spot check the OIP's for the Staff Pick Template's -- that's where i found the missing mData in "Invalid Quantity"

**Comment by aaronschachter** [comment]
Changed this issue title -- I've found another Opt-in path where members can get stuck if a mData isn't connected to it, which is the "MMS Not received."  Our test campaign was copied from the Staff Pick template and is missing an mData to respond back when a member incorrectly submits a photo:

<img width="660" alt="screen shot 2016-08-22 at 9 14 52 am" src="https://cloud.githubusercontent.com/assets/1236811/17862241/40737736-6849-11e6-9446-38ac5cc6e078.png">

**Comment by classicfreddie** [comment]
Thanks Aaron! I believe we have added this to any active campaigns, but
good for us to double check. James - can you make sure MMS not received opt
in path for active campaigns has the mdata connected?

Freddie Bologno

Mobile Product & Messaging Manager
@dosomething <http://twitter.com/dosomething> @classicfreddie
<http://twitter.com/classicfreddie>
(212) 254-2390 x 214

**Comment by aaronschachter** [comment]
This won't be an issue now that we're using a single mData to run a Campaign. #655
