### ISSUE TITLE
Introduce standard logging

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/gambit#562]
_BUG_
-------------------
#### Current Behavior
This app logs messages to one MongoDB collection and exceptions to another. Because these aren't standard logging facilities, they don't

- Get rotated
- Funnel to ELK
- Trigger alerts
- Make themselves visible to anyone

#### Desired Behavior
- Find a standard log service that we can [funnel to ELK](https://www.google.com/search?q=heroku+logging+logstash).

cc @blisteringherb 

### TODO
Updated 10/18
* [x] Use one `logs` collection
* [x] Send to logstash

**Comment by deadlybutter** [comment]
For reference https://devcenter.heroku.com/articles/log-drains

Just need to coordinate with Morgan on the credentials & testing it works

**Comment by deadlybutter** [comment]
Related devops work: https://github.com/DoSomething/devops/issues/220

**Comment by aaronschachter** [comment]
We're storing all logs in a `logs` table, and it sounds like we're good to go on Logstash. Potential last task would be to configure alerts if we don't have already -- Heroku sends emails about percentage of failed requests, and we've got New Relic configuration setup too.

@mshmsh5000 @blisteringherb Sound ok to close this one?

**Comment by blisteringherb** [comment]
👍 We're also using PagerDuty now, so we might want to look into configuring that to escalate issues to the Gambit team.
