### ISSUE TITLE
Refactor "Chat ended" Opt-in path into Success/Fail OIP's

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#588]
This feels like worthwhile bookkeeping on the Mobile Commons side. We currently opt all members into a single `oip_chat_ended` when our bot is done listening, regardless of things going right or wrong.  Suggest we use two OIP's instead of 1:

`oip_success`:
* Donation is completed
* Donated too many times

`oip_failed`:
* DonorsChoose API is down
* DonorsChoose account out of $$
* etc

This does bring up a question of whether separate Mobile Commons campaigns for each state (Chatting, Success, Fail) would enable us to broadcast to members in each, e.g 
- Chat campaign: "Hey, we saw you never finished your Science Sleuth Donation, please text KEYWORD to unlock it!"
- Failed campaign broadcast: "Whoops, sorry about the other day but we've fixed that. Please text KEYWORD to finish your donation"
- Success campaign: "Did you know you can donate again? Text GAMEKEYWORD to play again!"

I'm not 100% on this but I think keeping members within the same MoCo Campaign (using the different OIP's) doesn't allow us to MoCo broadcast like this.
Might not be needed for Science Sleuth this year, but brainstorming on ways we can improve SMS reportbacks (#463)

cc @classicfreddie @jamjensen @mshmsh5000

**Comment by mshmsh5000** [comment]
Any way to differentiate status is 👍 from me. As long as that doesn't make downstream messaging / segmenting more difficult for us—but I can only imagine scenarios where the two OIPs make it easier, not harder.
