### ISSUE TITLE
Send SMS Campaign Signup confirmation when member signs up via web and has Mobile Commons profile

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#642]
This might be a way to support Signup confirmations from CampaignBot when the Signup is being created from a non-Gambit source (web, email, mobile app, etc).

* [x] Support posting a `signup_id` and `signup_source` to `chatbot`, to send a `chatbot` message to given Signup User for Signup Campaign
* [ ] Change Quicksilver to post our any new User registration or Signup creations to new Gambit endpoints directly instead of posting to Mobile Commons API, with `send_confirmation` set 
* [x] Add a new CampaignBot property named something like `menu_signedup_external` -- We want different signup confirmation copy for when a member signs up via SMS keyword vs. web. Rename current property as `menu_signedup_gambit`
* [x] Upon a POST Signups request, CampaignBot sends its `menu_signedup_external` message to the User
* [x] Add check for incoming POST requests -- only send a confirmation message if the Campaign is an active CampaignBot campaign defined in `CAMPAIGNBOT_CAMPAIGNS`

If we ever wanted to run 20 DS Campaigns at once over SMS, it brings up the many-signups-single-transactional confirmation QuickBit cc O'Doyle

cc @sergii-tkachenko @justkika  @classicfreddie  @jamjensen 

## How it works now

When a member signs up for a DS Campaign (id 362) on web and Campaign 362 has a unique Mobile Commons Opt-in Path (OIP) set, e.g. Staff Picks -- Quicksilver sends a signup confirmation SMS message to the member if we have their phone number.

Behind the scenes, Quicksilver is posting to the Mobile Commons API using that OIP to subscribe the member to a unique Mobile Commons Campaign we set up for current run of our DS Campaign 362.

The OIP we posted to sends a "You're signed up for Campaign Name! Let's get started" message to the member.  This copy is set by editing the OIP Conversation in the Mobile Commons admin UI.

Our DS Campaign's Mobile Commons Campaign contains several OIP's -- one for each type of message we send (Ask for quantity, Successful reportback, etc)

We also set up a unique Mobile Commons mData per DS Campaign name, which posts to our  `/reportback/:campaignName` legacy endpoint and used by all OIP's to send us incoming messages from the member.  Gambit legacy inspects the incoming message and responds back to the member by posting them into a different OIP (e.g. the OIP we have set for `ask_why` or `invalid_photo`)

## CampaignBot

For CampaignBot, we only want to use 1 mData and 1 Mobile Commons Campaign to handle all DS Campaigns and Reportback chatbotting.

#633

**Comment by aaronschachter** [comment]
It'd make sense to update the Gambit `/signups` endpoint/cache upon a web (or mobile app) Reportback Submission too.

**Comment by mikefantini** [comment]
@aaronschachter potentially dumb question but just want to make sure that this specific use case is covered in this scenario:someone who is not yet a member, comes to the site,  but I just wanted to make sure that this use case is covered under this scenario.

**Comment by aaronschachter** [comment]
No worries @mikefantini, we should be covered in that use case: the post to Gambit API cache update will be triggered by the Signup creation, which we can't create unless we have User ID. In that use case, the User registration occurs before we create the Signup (to store the new User ID).

**Comment by mikefantini** [comment]
Cool yeah that's what I thought but just wanted to make sure I wasn't incorrectly assuming anything. Thanks @aaronschachter.

**Comment by aaronschachter** [comment]
Added a new tasklist item for a new `msg_menu_external_signup` CampaignBot field to respond with different copy than a regular SMS keyword signup.

**Comment by aaronschachter** [comment]
Ideally the POST Gambit `signups` endpoint accepts these data fields:

* `campaign` -- numeric Phoenix Campaign ID
* `user` -- string Northstar User ID
* `signup` -- numeric Phoenix Signup ID
* `reportback` -- numeric Reportback ID (when posting to update with a Reportback Submission)
* `quantity``

**Comment by aaronschachter** [comment]
Closing this issue - last task should be completed via Quicksilver.
