### ISSUE TITLE
All of the tests.

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/gambit#671]
Let's get some test coverage going!

**Comment by deadlybutter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automated testing](https://trello.com/c/L9VRuulF/8-automated-testing)

**Comment by aaronschachter** [comment]
Reopening this as we've begun work on testing: #864, #865, #867, #868, #869

**Comment by rapala61** [comment]
@aaronschachter should this issue stay open now that we have over 17% test coverage in Gambit? If its going to remain open, I guess we should add some goals to this ticket.
