### ISSUE TITLE
Create Doing/Completed Mobile Commons Groups for a DS Campaign Run

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#673]
Refs https://github.com/DoSomething/gambit/pull/672#issuecomment-255138491

When a new Campaign is cached, create [2 new Mobile Commons Groups](https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API#createGroup) if they don't exist already with names
*  `campaign_[id]_run_[id]_doing` -- stores Users who haven't completed the Campaign yet
* `campaign_[id]_run_[id]_completed` -- stores Users who have completed the Campaign

We'll use these Mobile Commons Groups to segment our Mobile Commons broadcast messaging.

When a Gambit Signup document is created, add the User to the `signedup` Mobile Commons Group.
When a Gambit Signup is updated (which could happen from a POST #642) and the User has reported back, remove them from the `signedup` MC Group and add them to the `completed` Group.

**Comment by aaronschachter** [comment]
We talked through how to implement today, and Quicksilver will handle adding/removing members to the relevant Doing/Completed groups. If Gambit handled this, Quicksilver would need to POST Reportback activity anyway (in order to move any Doing's into Completed if they reported back via web).

I was hoping we'd be able to use the Group machine name for adding/removing, but we need to pass the numeric Mobile Commons Group ID when [adding or removing](https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API#AddGroupMember). 

One idea here is that when we add a new Campaign to Gambit's list of active campaigns (`CAMPAIGNBOT_CAMPAIGNS`) -- Gambit creates the groups if they don't already exist and could expose the ID's on a new GET Gambit `campaigns` endpoint exposing our campaign documents. 

Another idea could be for Quicksilver to [GET groups](https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API#ListGroups) and parse the list looking for the correct group by its name (`campaign_id_run_id_doing`) results... but I think a GET Gambit `campaigns/:id` to find the correct Mobile Commons Groups sounds cleaner.

cc @sergii-tkachenko

**Comment by aaronschachter** [comment]
This branch starts on creating the Mobile Commons Groups per DS Campaign upon app launch.  I could see a use case for also exposing the Campaign `keywords` and msg overrides defined in the Gambit document in a Gambit campaigns API as well.

Another idea that I'm not crazy about is just manually creating the Groups in Mobile Commons and storing their ID's in the Phoenix Third-party Opt-in form (replacing the Mobile commons OIP field with 2 fields to store Doing/Completed groups...but it'd be a lot nicer to automate the DS Campaign / Group ID associations to avoid potential epic subscription fails when entering the wrong Group ID.

cc @deadlybutter

**Comment by aaronschachter** [comment]
Chatted about this issue with @sergii-tkachenko today -Quicksilver will retrieve the Group ID's it needs from new Campaigns endpoint #677.  #674 added auto-creating of the groups, so closing this to continue working on exposing group id's in #677.

**Comment by aaronschachter** [comment]
This issue could use some cleanup:

* [ ] Delete `mobilecommons_group` and `mobile_commons_group` properties from DB, refactor as `mobilecommons_group_doing` and `mobilecommons_group_completed` properties per #681 

* [ ] Only log the `mobilecommons.createGroup` message if we're creating/storing new groups. If the campaign document doesn't have a group stored and we get the Mobile Commons error of invalid name.. worst case is we could GET https://secure.mcommons.com/api/groups and search all results for the name... 

* [ ] Would make sense to add a pull staging DB script (https://github.com/DoSomething/gambit/blob/2.1.0/pull_config.sh) to have Thor/Prod apps responsible for the Group generation (vs localhost)

* [ ] Delete test Mobile Commons Groups 
<img width="649" alt="screen shot 2016-10-25 at 10 04 26 pm" src="https://cloud.githubusercontent.com/assets/1236811/19713960/12883512-9aff-11e6-82d8-0fe22be436fe.png">

**Comment by deadlybutter** [comment]
@aaronschachter in most of our API responses we group similar fields together, why are we creating lots of single independent fields instead?

Also I would probably throw in a veto for fetching all groups. we have over 10 thousand if I remember right, and none of them are actually deletable. I can't see the mobile Commons docs on my phone but when I get in I'll try & think through some ideas with you.

Also I don't know if I like the idea of mixing Thor/local groups, but we might not have much of a choice
