### ISSUE TITLE
Campaigns API response tweaks

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#681]
- [x] Remove the `__v` property which we never set in Gambit
- [x] Change `_id` to `id`?
- [x] Restructure `mobilecommons_groups` object as `mobilecommons_group_doing`, `mobilecommons_group_completed`
- Rename `keywords` as `mobilecommons_keywords` to make more specific

cc @sergii-tkachenko

**Comment by deadlybutter** [comment]
> Change _id to id?

Not a fan of this. We don't do this with Northstar user models & I'd really like to keep API responses consistent.

**Comment by aaronschachter** [comment]
@deadlybutter I mean changing it to `id` for our GET campaigns response, not changing the field in Mongo.
Northstar API returns a User `id`: https://github.com/DoSomething/northstar/blob/dev/documentation/endpoints/users.md

**Comment by deadlybutter** [comment]
OH im sorry, the title went over me
