### ISSUE TITLE
Lookup User ID for mobile number in every request (vs using stored Northstar ID MC Profile field)

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#691]
The `chatbot` router currently checks [if we have a Northstar ID stored on the incoming Mobile Commons Profile](https://github.com/DoSomething/gambit/blob/develop/app/routes/chatbot.js#L72), to avoid fetching the User ID every time. We've already run into some bugs for internal staff members: The Northstar User ID on @hbghidey's Mobile Commons Profile (175753518) has this id stored for northstar ID: 55442907469c64ed7d8b480a. If you lookup that NS User, you'll see there's no mobile number, and a DS email. The Signup worked as expected, the Mobile Commons message was never delivered because we didn't have a mobile number for her user. Yet if you lookup a NS User for her mobile, its 5612a109469c64bc348b4f36 with a gmail address.

Here are ways a Northstar ID can exist on a Mobile Commons Profile:

* Quicksilver import scripts we ran for vCard to generate ID's and save to the field (to use within Liquid in a soon-to-be-legacy-MobileCommonsCampaign)

* Gambit updates it upon saving the `gambit_chatbot_response` Custom Field, [only when it doesn't exist](https://github.com/DoSomething/gambit/blob/develop/app/models/User.js#L134)

* Any Mobile Commons admin can edit this value via UI

I've seen 2 staffer instances that needed Northstar ID's cleared in their MC Profile to fix Gambot message failure, and suspicious it may be causing #679.

For CampaignBot v1 I think it's worth calling the extra GET users request to get Northstar ID for the incoming mobile number for every incoming mData request, as the incoming mobile number won't be so easy to change. It should also let us switch between testing Thor and Production Gambit environments without as much potential for ID mismatch.

cc @sergii-tkachenko @deadlybutter @DFurnes

**Comment by deadlybutter** [comment]
>  Yet if you lookup a NS User for her mobile, its 5612a109469c64bc348b4f36 with a gmail address.

This is the case with my profile as well because it got associated with a non DS test account.

In general, I don't like the idea of increasingly building ties to Mobile Commons. We should determine why there are phone number mismatches & resolve those problems. Given that, I don't think we should be afraid of asking Northstar to identify a user based on mobile number upon request.

**Comment by aaronschachter** [comment]
Thanks for the input @deadlybutter -- 💯 . The more I think on it, the more it feels less an "idea" issue and "let's get this in asap" issue. Always querying NS for the UID would remove the MC Profile field out of the mix for resolving out identity/mobile issues, and it sounds worth it to me.

Also here's a fun fact, @kerigoff, star of https://github.com/dosomething/gambit/issues/679#issuecomment-256753010, has a MC Profile where the Northstar User stored has no email associated with it (according to Aurora), just a mobile: https://thor-aurora.dosomething.org/users/577f0cd8469c64652b8b4627 and source `phoenix`
