### ISSUE TITLE
Messages collection

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#698]
Log each incoming request, and how Gambit responds.

* `_id`
* `client` -- `'mobilecommons'`
* `client_message_id` -- Mobile Commons `message_id`
* `client_sender_id`-- Mobile Commons `profile_id`
* `client_broadcast_id` -- Mobile Commons `broadcast_id`, set when User is responding to a broadcast message
* `phone`
* `incoming_message`
* `incoming_image_url` -- Media url?
* `response_message_type`
* `response_message`
* `user` -- DS Northstar User ID
* `current_campaign` -- DS Campaign ID we save to User upon sending response

**Comment by aaronschachter** [comment]
This issue came out of our data sync on last Friday. I'd imagine we could get this data by querying the Mobile Commons API -- but it could make sense to store our own `messages` collection to track incoming messages and how Gambit responds, especially if we ever add FB Messenger support to Gambit.

Not sure if this is necessary to implement, but wanted to create the issue to document #quasar concerns in our sync from Friday. My $0.02 would be to create a `collections` to store all sent CampaignBot messages and replies, vs storing a timestamp property on the User.

**Comment by aaronschachter** [comment]
@sheyd -- This collection will start populating upon our deploy of a new 3.2.0 release today. It's going to be super helpful for Gambit messaging analytics -- but also super important to **not run expensive queries on production**, esp with #704 still open and unknown.

Any way we can start feeding data from the Gambit DB into our DS data warehouse? This `bot_requests` collection will provide answers for how many Signups result from a Mobile Commons Signup Broadcast.

**Comment by sheyd** [comment]
@aaronschachter This would have to be out of band work for this sprint. I'd have to setup a new pipeline from Gambit into our DS warehouse, which we're in the process of migrating into a new environment this sprint. I think the priority should be to get this in on our next sprint.

**Comment by aaronschachter** [comment]
Sounds good @sheyd. It does bring to mind the ol' extra information on the Signups table conversation we had a tech team meeting about a while back. The incoming Mobile Commons `broadcast_id` would be nice to store on the Signup as well.
