### ISSUE TITLE
Post incoming Mobile Commons Profile created_date to Northstar User

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#699]
Send to `created_at` or wherever appropriate

cc @sheyd

**Comment by sheyd** [comment]
I like the idea of using a different field like `sms_created_at` instead of over-riding the default Northstar `created_at` date so we don't have data loss, and can track down actual Northstar creation date vs mobile creation/entry date. After chatting with @bladt and @nmccormick619, they are of a similar mind.

Curious on your thoughts @DFurnes on adding an additional field to 🌟 collections?

**Comment by aaronschachter** [comment]
One idea here is that if we're **not** looking to override Northstar `created_at` -- then we can at least store the Mobile Commons `created_at` value locally in the Gambit Users db -- and won't be blocked on anything Northstar API.

**Comment by aaronschachter** [comment]
This feels like an issue would Northstar / Mobile Commons scraper could resolve once it's live, which sounds soon.

Per @DFurnes in https://dosomething.slack.com/archives/api/p1477684868001167:
> MobileCommons SMS-only users who have never reported back are probably another large group, once we get the syncer service up and running on production (this or next sprint).

**Comment by aaronschachter** [comment]
Chatted with @DFurnes about this today to review... it sounds like the DS Mobile Commons scraper should be running within a sprint or two, and would like a better place to store the central logic for determining source of truth of a user's `created_at` date.  This would especially come up if/when we get around to merging members who have a DS User created for their email, and then a 2nd DS User created for their mobile number with a `@mobile` or `@mobile.import` email.

Gambit currently creates the minimum user profile it needs to work:
* [`mobile` and `mobilecommons_id`](https://github.com/DoSomething/gambit/blob/7e3e199904507d2f77195ea0c734c68b74e93ed3/app/routes/chatbot.js#L7) from Mobile Commons profile
* [Code-generated `source`, `email`, and `password`](https://github.com/DoSomething/gambit/blob/7e3e199904507d2f77195ea0c734c68b74e93ed3/app/models/User.js#L78)

I need to verify posting locally from an mData to confirm -- but I've looked over the email alerts we receive when MC errors occurs, and they suggest that `created_at` is not passed in an incoming request body --  which could require making an additional  GET request to MC profile endpoint to find the profile's `created_at` in order to implement this issue.

cc @sheyd What do you think? If all sounds good, I think we can close this one with a NO label...

**Comment by sheyd** [comment]
Closing this out in favor of the MC Northstar scraper being the best way to set `created_at` date when it's live in a sprint or two.
