### ISSUE TITLE
Groups cleanup

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#708]
* [x] [Add `lib/groups.js` for linting](https://github.com/DoSomething/gambit/blob/02c84f8b346c838c157ea3a31552d2db4cc3ab17/package.json#L13)
* [x] Log err.message if DS Messaging API key doesn't exist instead of empty error -- see attachments
* [x] Remove `mobilecommons.createGroup`function if we're no longer using it (we're not, right? the DS Messaging Groups API handles?)
* [ ] DS Messaging Groups API: If the create group call fails, query the GET groups by name to find its ID (new MC API feature per support ticket #124466)
* [ ] Lower priority -- but DRY cleanup? My $0.02 is if code can be cleaner, we should clean it: https://github.com/DoSomething/gambit/pull/697/files/1f88a857619cecf03104bc078b93b9c71fbc1241#r85604276

cc @sergii-tkachenko 

## Attachments
<img width="866" alt="screen shot 2016-10-29 at 8 07 23 am" src="https://cloud.githubusercontent.com/assets/1236811/19837650/710f94d4-9e7b-11e6-9932-8455e02201d6.png">

**Comment by deadlybutter** [comment]
> DS Messaging Groups API: If the create group call fails, query the GET groups by name to find its ID (new MC API feature per support ticket #124466)

Ill make the issue in the other repo for that

>  Lower priority -- but DRY cleanup? My $0.02 is if code can be cleaner, we should clean it: 

Can you elaborate on what we need to cleanup where you linked? You also linked to a separate commit that doesn't reflect what was merged so maybe you're referring to something already covered in the PR review?

**Comment by aaronschachter** [comment]
Sounds good about new issue in DS Messaging Groups API repo.

Re cleanup -- from https://github.com/DoSomething/gambit/pull/697/files/1f88a857619cecf03104bc078b93b9c71fbc1241#r85604276:
> That's actually a bad idea to handle the error here

@sergii-tkachenko can chime in here, it seems like he was requesting changes that we didn't add for sake of time -- but we do have the time now. Big part of this rewrite is making sure our code is beautiful 🌅

**Comment by deadlybutter** [comment]
Sergii wanted to add custom error handlers, but as of now (and any future i can see) there is no value in doing so given the unique usage of this feature.
