### ISSUE TITLE
Instrument basic StatHat coverage

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/gambit#714]
Let's get StatHat coverage for the basic events in Gambit: signups, reportbacks, maybe errors?

**Comment by aaronschachter** [comment]
Keeping this open until we add alerts for any misconfiguration that can go down (and trigger emails). Some examples:
- Keyword is live for a closed (or unpublished) Campaign
- Keyword doesn't have a matching Campaign for it in the active CampaignBot campaigns
- The Signup Broadcast Campaign is closed or not found

**Comment by jamjensen** [comment]
I wanted to have more of a dashboard feel when trying to figure out what's happening in Gambit so I made some StatHat cards. 

- All error messages sent at different stages of user flow: https://www.stathat.com/cards/ZnGN4DygwRmz 
- Number of completed report backs vs number of report backs started: https://www.stathat.com/cards/FoOK5awF6lx1
- Signup Broadcast performance: https://www.stathat.com/cards/5ud5uYFBcAiV 
- Total number of signups to campaignbot: https://www.stathat.com/cards/JEfBaT43Rr4V
- User flow broken down by each message (Quantity, Photo, Caption, Why Particpated): https://www.stathat.com/cards/0oH9GyyId8KS

**Comment by mshmsh5000** [comment]
Beautiful!


CTO
@mshmsh5000 <http://twitter.com/mshmsh5000> @dosomething
<http://twitter.com/dosomething>

**Comment by aaronschachter** [comment]
I think we're in decent shape to close this -- we're tracking errors in Stathat, New Relic -- and errors returned to our mData show up in Slack, with more descriptive messages per #825.
