### ISSUE TITLE
Update logic for Yes response

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#717]
Current `isYesResponse` function (that we used for "Can you send photos from your phone?" legacy `/yes-no-path` endpoint) [works this way:](https://github.com/DoSomething/gambit/blob/031b37ace0fdb650ac516aabc9b3d9b19cd714ab/lib/helpers.js#L163
)

If the first word isn't  'N', 'NA', 'NAH', 'NO', or 'NIL' (not case sensitive)-- consider the response a Yes. This added in #598 was to handle #513 -- adding support for different Yes variations like "sure", "of course", "ya", etc

Need product team to confirm logic or specify requirements. If we need to change current behavior, then this issue can remain open until we implement the changes in code.

Refs #651

**Comment by aaronschachter** [comment]
@jamjensen @classicfreddie Seperate issue but related -- it'd be useful to document (and change, if we need to) how we verify Caption and Why Participated as well. The current validation check is that the response sent must be at least [4 characters long and contains letters.](https://github.com/DoSomething/gambit/blob/fb39f361f1cf3e0e8716d02abf1b4cc3199194fe/app/controllers/CampaignBotController.js#L48)

**Comment by jamjensen** [comment]
@aaronschachter current logic for y/n responses: 

![image](https://cloud.githubusercontent.com/assets/19572934/20019176/64580e2c-a2a1-11e6-90a6-3367f6e1d504.png)

**Comment by jamjensen** [comment]
re: how we verify Caption and Why Participated -- we don't. Whatever the member responds with to each of those questions is what shows up on the backend. 

We're seeing that Why Participated is getting cut off for users whose Caption response is more than one message. In this user's reportback (https://www.dosomething.org/admin/reportback/206530) you'll see that the Why Particpated" is the continuation of her Caption.  

Here is her MoCo profile to view her text history: https://secure.mcommons.com/profiles/208632319 
Gambot registers the first message she sends as her response to Caption, asks here Why she participated, then records the additional messages for caption as her answer for Why.

**Comment by aaronschachter** [comment]
Thanks @jamjensen -- the user's sent message being too long is a separate issue (there's a potential way to solve this in #635, which is def not a small t-shirt size)

Do we have access to edit those YES/NO responses in Mobile Commons?

**Comment by jamjensen** [comment]
No, sadly we do not. We've had to ping MoCo when we want to yes/no to accept additional phrases. 

Small T-shirt to add phrases to Gambit's y/n logic?

**Comment by aaronschachter** [comment]
Shirt size for that question depends on what action we take when the User texts back a word that is neither in the list of Yes responses or No responses, or only an image -- no words.

**S**: Count it as either a yes or no.

**M/L**: If we can't understand as yes/no, respond back with "I didn't get that" -- but then we need an additional CampaignBot property, something like `msg_invalid_signup_broadcast_command` to re-ask whatever the broadcast message is asking (and keep responding with it until they say either a Yes, No, or opt out with a member support command)

**Comment by jamjensen** [comment]
@aaronschachter 

I think I'm leaning towards responding back with "I didn't get that..." 

What are you thoughts on this: 
If the member responds with a messages that's not yes/no, they receive "I didn't get that. Text back {{keyword}} if you want to {{tagline}}" Then if they don't respond with a KW they receive "Sorry I don't understand. If you have a question text back {{support_command}}

**Comment by jamjensen** [comment]
*Yes Responses*
Accepts 1, ABSOLUTELY, CORRECT, DEFINITELY, HM SURE, I DID, I CAN, OK, OKAY, SURE, TOTALLY, TRUE, T, Y, YA, YAS, YASS, YASSS, YASSSS, YASSSSS, YASSSSSS, YESS, YESSS, YESSSS, YESSSSS, YESSSSSS, YES, YEA, YEA SURE, YEAH, YEP, YUP, HELL YES, HELL YEAH, SI, S, Sí, SO, CLARO, OUI, OUé, and OUAIS for 'Yes'

**Comment by aaronschachter** [comment]
Chatted with @jamjensen about this and repurposes this issue to make code changes.

We'll roll with Small T-shirt for MVP and to close out #651 and change the logic in `helpers.isYesResponse` to return `true` if the first word matches one of the responses above.

To keep things super simple for now, let's store the Yes responses in a GAMBIT_YES_RESPONSES config variable.

A future releases should direct No responses to a yet-to-be-built Select Campaign menu (which we also need for #713 )
