### ISSUE TITLE
Investigate Campaigns.campaignbot logic in Campaigns API response

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#724]
Reviewing http://ds-mdata-responder.herokuapp.com/v1/campaigns?campaignbot=true and expecting all `campaignbot` properties to be `true` -- but displays `false` for just one Campaign, id 7277.

Checked on production and Campaign 7277 is set to active.

<img width="738" alt="screen shot 2016-11-07 at 6 48 51 am" src="https://cloud.githubusercontent.com/assets/1236811/20061900/96169138-a4b6-11e6-8bfd-ab29013b3965.png">

**Comment by aaronschachter** [comment]
I can't replicate this, and pretty stumped on why this occurred. Hoping it's just a weird browser cache issue and closing for now.

**Comment by jamjensen** [comment]
Are we able to determine that Ben is the only one who received the undefined message?  I've seen nothing in Agent View to suggest otherwise

**Comment by aaronschachter** [comment]
@jamjensen The undefined message issue is #736 -- this is just a anomaly I found where I expected the `campaignbot` property to be `true` instead of `false` in screenshot above, and can't replicate.
