### ISSUE TITLE
Allow external applications to send SMS

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/gambit#760]
External services should be able to `/notify` Gambit with a NS User ID & a message to send.

- [ ] Add routes file for notifications
- [ ] Find the phone number for given NS user
- [ ] Send the given message to the found NS user

**Comment by deadlybutter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'reminder messaging' field to Gambit](https://trello.com/c/WxRqEnrI/4-add-reminder-messaging-field-to-gambit)

**Comment by aaronschachter** [comment]
Added a comment in the linked Trello card about the need to spec out how Gambit delivers the message through Mobile Commons. If you're not planning on delivering the message via the `profile_update` endpoint that posts to the Chatbot OIP, #635 discusses possibilities for using the `send_sms` / `send_mms` endpoints

**Comment by deadlybutter** [comment]
@aaronschachter Yep -- we're going w/ option 2 using send_sms to get this out the door quickly, we're just going to include the keyword in the relative reminder for the moment
