### ISSUE TITLE
Better mobile commons default timeout

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/gambit#762]
```
RequestRetry.setDefaults({ timeout: 120000 });
```

2 minutes is quite long, if MC went down we'd pile up a lot of requests & potentially crash Gambit

**Comment by aaronschachter** [comment]
@deadlybutter @sergii-tkachenko Any suggestions for what to set it to?

**Comment by deadlybutter** [comment]
I prefer the fail fast way of thinking, I think it would help to know what there average response time is though, and add a small buffer to that value

**Comment by aaronschachter** [comment]
Per #862, end goal is for Blink to handle delivering the SMS to end user via Mobile Commons POST. Closing this one as a NO as it won't be handled by Gambit in near future.
