### ISSUE TITLE
New Users from CGG (still) unable to signup for Campaign via SMS 

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/gambit#769]
_BUG_
-------------------
#### Current Behavior
- As of 2:49 on December 7th, thanks to Dave's fix -- which, is outlined here:https://trello.com/c/kIvMHGsr/202-unplanned-work-fix-issues-caused-by-celebs-gone-good-users-not-having-drupal-ids -- we're creating phoenix accounts for new users coming from CGG and their ids are appearing in gambit. 

Unfortunately, despite having a phoenix id, new users from CGG text INSPIRE (the Say it with the Stars campaign keyword) and receive the mdata error message. 

![image](https://cloud.githubusercontent.com/assets/19572934/21024553/f3e05218-bd52-11e6-920a-5ecbe5680d49.png)

#### Desired Behavior
- The new user from CGG should have texted in INSPIRE and received the campaign signup message. 

![image](https://cloud.githubusercontent.com/assets/19572934/21024643/4dec9b72-bd53-11e6-8b05-91747d76e625.png)

#### Steps to Replicate
- how can you make it happen every time? 

Trying to figure that out... 

#### Why This Matters
- They are unable to sign up for the campaign, they have a terrible first experience with the product, they are unable to sign up for future campaigns via SMS, they are less likely to re-engage and think highly of DoSomething.

#### Relevant Screenshots + Links

Affected users: *as of 12/08/16* 

- https://secure.mcommons.com/profiles/211080958
- https://secure.mcommons.com/profiles/170790569
- https://secure.mcommons.com/profiles/211077472
- https://secure.mcommons.com/profiles/211082116
- https://secure.mcommons.com/profiles/175881415
- https://secure.mcommons.com/profiles/211085566

All of the above users have a phoenix id, which also appears in gambit.

**Comment by jamjensen** [comment]
- 14 users received the error message from 12/7/16 at 2:30pm until 12/8/16 at 4:30pm.

**Comment by jamjensen** [comment]
@DFurnes @deadlybutter I am able to confirm that including emojis in your first name does affect users ability to sign up for a campaign via sms.  In the screenshot below you can see emojis including in my first name, right next to >Profiles. After texting INSPIRE I received the error message, which was to be expected. 

Since we implemented the fix: 
- 14 users have received an error message (due to emojis + other unknown edge cases) 
- 32 new users from CGG have signed up for a campaign over SMS 

![image](https://cloud.githubusercontent.com/assets/19572934/21028998/aa4c6a84-bd65-11e6-9116-c6012fbf451b.png)

**Comment by jamjensen** [comment]
I was able to find a Phoenix id listed in gambit (for the profile that has emojis in my first name), but when I searched Phoenix it was nowhere to be found. 

![image](https://cloud.githubusercontent.com/assets/19572934/21032258/693bfa76-bd76-11e6-8594-d530c5316033.png)

**Comment by jamjensen** [comment]
- From 9:53am EST on 12/8, users were no longer able to text INSPIRE and sign up for Say it with the Stars. (Campaign keyword was changed in campaign mongo doc)
- The last successful signup (from new CGG user or otherwise) occurred at 9:47 AM EST

**Comment by aaronschachter** [comment]
@jamjensen @deadlybutter Does it make sense to close this issue? These errors seem related to existing Northstar/Phoenix accounts, and don't seem like Gambit code changes...

**Comment by deadlybutter** [comment]
Yeah you can close this
