### ISSUE TITLE
Disabling Relative Messages triggers errors and New Relic alerts

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#773]
We've been seeing a wave of New Relic alerts because QS is attemping to post to the `/campaigns/:id/message` endpoint for campaigns that have had their `messages` removed from the document.

@jamjensen removed them to avoid [sending multiple relative reminders during NYNU](https://dosomething.slack.com/archives/gambit/p1485187951000074).

Best way to turn off relative reminders would be to build out a kill-switch as a feature, otherwise we're stuck with NR alerts from all the 422 errors.

**Comment by deadlybutter** [comment]
If there is no campaign matching the given ID, that should return a 404, not a 422. I'd reference Northstars list https://github.com/DoSomething/northstar/tree/dev/documentation#errors--status-codes

Also, why does New Relic throw errors when we post back a 4xx? Is it only for certain error codes? I don't think any other services do that for a 400 error?

**Comment by aaronschachter** [comment]
The campaigns are found -- they are just missing the `messages` property, which is why its a 422: https://github.com/DoSomething/gambit/blob/7f504dcf7206900e8671d30396b32f8ada88d3c0/app/routes/campaigns.js#L76

cc @sergii-tkachenko who added this functionality.

If we turned off New Relic for all 4xx -- that'd help with the alerts in #696. I'm fairly sure we don't throw them for 404 codes.. but throwing errors for 422 I think is New Relic default behavior (but not certain)

**Comment by deadlybutter** [comment]
Weird (On New Relic) -- If it was a 5xx I'd say yeah, throw an error, but 4xx??

**Comment by aaronschachter** [comment]
Looks like we can filter error codes here: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#error_ignore but looking into this more, and it seems like the alerts are triggered from slow response times and not the 422's. I think this is a duplicate of #704.

**Comment by aaronschachter** [comment]
Hmm, maybe the errors are triggering the apdex alerts -- seems to always get both. Reopening this to hopefully close out by ignoring 4xx error codes in NR.

**Comment by aaronschachter** [comment]
I've set the `NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES` to `404,422` -- by default it only [ignores 404](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#error_ignore). cc @blisteringherb
