### ISSUE TITLE
Resolve Winston MongoDB issues, cleanup log/logs

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#774]
Noticing `index not found with name [timestamp_1]` [errors in New Relic](https://rpm.newrelic.com/accounts/108038/applications/25522350/traced_errors/06f10b22-e32e-11e6-b5b0-b82a72d2466d_0_1012/similar_errors?original_error_id=06f10b22-e32e-11e6-b5b0-b82a72d2466d_0_1012). Seems like a quick fix to [upgrade to 2.0.1](https://github.com/winstonjs/winston-mongodb/issues/75#issuecomment-266293720)

<img width="1220" alt="screen shot 2017-01-25 at 7 32 21 pm" src="https://cloud.githubusercontent.com/assets/1236811/22319145/08e7f992-e335-11e6-8329-0de9eba7049f.png">

**Comment by aaronschachter** [comment]
There is a `log` and a `logs` collection in the Gambit DB -- the `log` collection seems it was introduced by @deadlybutter in #753 when [upgrading to 2.0.0 and not specifying a collection name](https://github.com/winstonjs/winston-mongodb/blob/b4dbdb6cfca0376fd8566e5e787de743b86fcd79/lib/winston-mongodb.js#L72).

The last record in `logs` is from 2016-11-30 17:58:45.521Z -- but the `log` collection is empty, which suggests something is borked in the new configuration on production... locally post-docker I do see documents in `log` (and none in `logs`)

**Comment by sergii-tkachenko** [comment]
Ah, log/logs conflict still needs to be resolved.

**Comment by aaronschachter** [comment]
We've updated to 2.0.1 but still get this error in the logs:

> 2017-03-10T17:17:18.518173+00:00 app[web.1]: (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: index not found with name [timestamp_1]
> 2017-03-10T17:17:18.518238+00:00 app[web.1]: (node:3) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 2017-03-10T17:17:18.529335+00:00 app[web.1]: (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: index not found with name [timestamp_1]

**Comment by aaronschachter** [comment]
Taking a look at this oldie but a goodie and I see that our `log` collection is collecting entries:


`db.getCollection('logs').find({}).sort({timestamp: -1})`

<img width="794" alt="screen shot 2017-04-03 at 12 23 41 pm" src="https://cloud.githubusercontent.com/assets/1236811/24627117/9213ad98-1868-11e7-9e47-48e0190203a3.png">

but our `logs` stopped in 2016:

`db.getCollection('log').find({}).sort({timestamp: -1})`

<img width="754" alt="screen shot 2017-04-03 at 12 23 50 pm" src="https://cloud.githubusercontent.com/assets/1236811/24627126/97bd355c-1868-11e7-8168-3111cec9add9.png">


I'm also no longer seeing the `MongoError:  index not found with name ` show up in the New Relic errors.

Going to drop `logs` from staging and verify if it's gone for good. if so, dropping the `logs` from production DB should close this one out.

**Comment by aaronschachter** [comment]
Not sure how this started writing to `log` and the Mongo error went away, must be magic 🔮 
I've dropped the `logs` collection from production to close this.
