### ISSUE TITLE
Refactor Gambit chatbot endpoint to return success upon message received

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#776]
Refs https://github.com/DoSomething/gambit/issues/704#issuecomment-275727492

If we received a message, send a 200 "Message received" message back to Mobile Commons, to avoid timeout requests due to slow Northstar / Phoenix queries. We'll need to rely on New Relic and Stathat events/alerts to look out for events like failed Signups / user registrations (vs the mData alert).

**Comment by aaronschachter** [comment]
Backtracking on this for now. It's useful to know how long it takes for the messages to get to our end user, and doesn't seem to happen enough that we need to work on this first.

**Comment by aaronschachter** [comment]
Per https://github.com/DoSomething/gambit/issues/776#issuecomment-276420687:
> Backtracking on this for now. It's useful to know how long it takes for the messages to get to our end user

Yes, it is -- but we can keep a timer and store it some place like the `bot_requests` collection for example. I'm beginning to think this issue might be an epic win to avoid #810.

**Comment by rapala61** [comment]
After further discussion in #gambit. The magnitude of this timeouts warrant that Gambit returns a compulsory HTTP 200 to all incoming requests to out `/chatbot` endpoint.

**Comment by aaronschachter** [comment]
Currently when an error gets returned, the user will get the mData error message sent back from Mobile Commons.

We may want to add a new `errorOccurredMessage` to our Campaign content type in Contentful, as we'll want to use either the Mobile Commons `post_message` or the `User.postMobileCommonsProfile` function to deliver a message when an error occurs... assuming we do want to send a message back when an error does occur.

**Comment by aaronschachter** [comment]
Going back to the drawing board on this one https://github.com/DoSomething/gambit/pull/836#issuecomment-290863078 as we haven't been seeing the H12 timeouts (and haven't made any significant code or environment changes to cause this -- just making sure to restart dynos, which may or may not be helping)...
