### ISSUE TITLE
GET campaigns response is broken

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#808]
// 20170308131524
// http://ds-mdata-responder-staging.herokuapp.com/v1/campaigns

{
  "error": {
    "code": 500,
    "message": "expecting an array or an iterable object but got [object Null]"
  }
}

**Comment by aaronschachter** [comment]
This started happening because some Contentful Campaigns were archived, but still have published Keywords:

<img width="1086" alt="screen shot 2017-03-08 at 8 37 25 pm" src="https://cloud.githubusercontent.com/assets/1236811/23732101/19181e5c-043f-11e7-9665-d39e226e90c2.png">

@jamjensen Is there a reason to archive Campaigns? I was under the impression we'd always keep them published (closed campaigns in Phoenix remain published, and accessible via API). Or was this an unintentional side effect of the Google Sheets + Contentful Zapier integration?

**Comment by jamjensen** [comment]
@aaronschachter I archived 2086 so that I'd be able to quickly see what campaigns are live this month. Is there a way to only view the campaigns that are currently live if all of them are published?

**Comment by aaronschachter** [comment]
There is! You can check http://ds-mdata-responder.herokuapp.com/v1/campaigns -- these are all campaigns that have published keywords defined in Contentful. This endpoint will be what a Slackbot uses, blocked by doing the work to build out the Slack [Slothbot](https://github.com/dosomething/slothbot) and #798

**Comment by jamjensen** [comment]
Right. I think right now - and this really would all change once slothbot is up and running - is that it's easiest and most effective to view all active campaigns consolidated by NID and sorted by the fact that they are published.
