### ISSUE TITLE
Automate FAQ Responses: Scholarship Due Date

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/gambit#821]
_FEATURE OVERVIEW_
-------------------
#### User Story
- One of the most common questions members ask is: When is the scholarship due?  Using `timing.high_season.end` from the campaign's API, we'd like to automate the response so that members can quickly find out the end date for any campaign that they are signed up for. 

- Potential MVP: when a member receive an error message  (presumably from asking a question when they should have texted either photo/quantity/why participated) they are told: "If you have a question, text Q." We could also say: "If you want to know when the scholarship is due, text S."  OR we could tell them to text FAQ to see a list of commonly asked question - and have scholarship due date be one of the responses.

#### Why This Matters
- Provides clarity to members who are unaware of the campaign deadline. In turn, can create a sense of urgency that could potentially increase reportbacks. 

#### Current Workaround w/o Feature (if applicable)
- Question is answered in agent view when bandwidth permits.

**Comment by jamjensen** [comment]
We'd also need to include the campaign keyword (or a command) in the response so that members are able to get back into the flow.

**Comment by justkika** [comment]
Maybe we should make another feature request for _all_ questions we can pull from endpoints? To see all in a list so that we can prioritize the order based on popularity/frequency.

**Comment by aaronschachter** [comment]
This will be handled in Rivescript via https://github.com/DoSomething/gambit-conversations -- but we're blocked until the Campaign's Scholarship Amount is exposed in the Phoenix Campaigns API, as we've mentioned before when discussing FAQ's.

cc @DFurnes
