### ISSUE TITLE
Collect Heap data to analyze and find the reason for Gambit Memory Leak

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#837]
_BUG_
-------------------
#### Current Behavior
- There is an steady increase in memory over time in Gambit.

#### Desired Behavior
- Collect Heap Snapshots from Gambit live and upload to S3 for offline analysis.

#### Steps to Replicate
- It happens all the time just by being up and running in Staging and Production. 
- It seems to have started after this pull request: https://github.com/DoSomething/gambit/pull/825

#### Why This Matters
- It might have a connection to some timeouts that are not due to external requests. See: https://github.com/DoSomething/gambit/issues/810#issuecomment-290148244

#### Relevant Screenshots + Links

- See:
   - https://github.com/DoSomething/gambit/issues/810#issuecomment-290148244
   - https://github.com/DoSomething/gambit/issues/810#issuecomment-290271825

_FEATURE OVERVIEW_
-------------------
#### User Story

As a O'doyle dev, I want to investigate Gambit memory leak so that Gambit doesn't crash.

#### Current Workaround w/o Feature (if applicable)

Heroku Dyno restarts before broadcasts and schedule restarts.

**Comment by rapala61** [comment]
Using Heroku Review Apps feature would be useful to test potential solutions. In fact, @aaronschachter originally used them, but decided to discontinue since it was unpractical to use with only one dev fully committed to Gambit and the staging app to play with all for himself. See here: https://github.com/DoSomething/gambit/pull/715

**Comment by rapala61** [comment]
@aaronschachter has given me the go-ahead to resurrect Review Apps. 🚥

**Comment by rapala61** [comment]
Steps i have already taken:

## Locally
- Start node with the --inspect flag so I can profile memory in chrome tools.
   - Took Heap profiles and compared. Some interesting Deltas showed up , but couldn't find anything in concrete.
   - After charting the process memory on each request for about 2 hours and not finding any upward trend that suggested a leak. The deltas seem to be false positives.
- Dump process memory on each request to observe used heap and free heap memory activity.
   - Outcome: levels fell down to normal after load.

**Comment by rapala61** [comment]
So after a very informative conversation with @pnasrat. The suggestion from #devops is:

1) "communicate there is a performance bug and you are going to do some explicit testing between x-y times." In ds-mdata-staging.

2) "get samples then move to offline analysis." This requires us to implement code that takes a heap  snapshot every x amount of minutes and send it to an s3 bucket. It should easily be turned off/on via an env variable.

@aaronschachter what do you think on this change of scope?

**Comment by aaronschachter** [comment]
Sounds 👍 to me -- definitely sounds great to loop devops on in this one. For #1 -- is the explicit testing on staging, or did you mean production?

**Comment by rapala61** [comment]
Not so fast! we still need to collect data and analyze offline.

**Comment by rapala61** [comment]
Documenting:

There are 3 Buckets in S3 that will hold these Heap Snapshots:
- local-v8-profiler.dosomething.org (For local dev environment Heap snapshots)
- staging-v8-profiler.dosomething.org (For staging environment Heap snapshots)
- v8-profiler.dosomething.org (For Production environment Heap snapshots)

**Comment by aaronschachter** [comment]
Mind updating the `.env.example` with `V8_PROFILER_S3_BUCKET=local-v8-profiler.dosomething.org` ? I just changed mine locally.
For tiny documentation changes like those, sometimes I just edit on `develop` on Github directly, for better or worse --but doesn't seem to warrant a PR.

**Comment by rapala61** [comment]
What about if I change it and commit with the release commit?

**Comment by aaronschachter** [comment]
Sounds good! perfect example of a commit to add into the release branch. From http://nvie.com/posts/a-successful-git-branching-model/#release-branches: 

> Release branches support preparation of a new production release. They allow for last-minute dotting of i’s and crossing t’s. Furthermore, they allow for minor bug fixes and preparing meta-data for a release (version number, build dates, etc.). By doing all of this work on a release branch, the develop branch is cleared to receive features for the next big release.

**Comment by rapala61** [comment]
Documenting:

Authentication errors started to appear in the logs if the Bucket used to store the snapshots was not `v8-profiler.dosomething.org`. @blisteringherb had to configure the other two buckets to have the right permissions to fix the problem.

Example of the error:
```
4:40:41 PM web.1 |  info: Upload Stream error: Failed to create a multipart upload on S3: {"message":"Access Denied","code":"AccessDenied","region":null,"time":"2017-04-04T20:40:41.917Z","requestId":"**********","extendedRequestId":"*************************************","statusCode":403,"retryable":false,"retryDelay":99.07656611167177}
```

**Comment by rapala61** [comment]
Update:

The profiler is up and enabled in `staging`. it's taking snapshots every hour.

**Comment by rapala61** [comment]
Heap data was collected in staging after https://github.com/DoSomething/gambit/pull/840 was merged. Heap snapshots showed large deltas of retained memory that pointed to our logger (Winston). This fact helped me locate the line of code in https://github.com/DoSomething/gambit/pull/825 that introduced the leak. 

My theory is that we should be requiring our logger in an alternative manner, looking at the documentation, I read this bit: 

"Now that your loggers are setup you can require winston in any file in your application and access these pre-configured loggers"

```
  var winston = require('winston');
 
  // 
  // Grab your preconfigured logger 
  // 
  var category1 = winston.loggers.get('category1');
 
  category1.info('logging from your IoC container-based logger');
```

But we are now grabbing the logger from `app.locals.logger` and re-exporting the same instance from the module. 

The more complex internals of why this is causing the mem-leak are not 100% clear to me, it is quite fascinating and really look forward to learn more from it.
