### ISSUE TITLE
POST Reportback fails if caption > 255

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#881]
_BUG_
-------------------
#### Current Behavior
If a `reportback_submission` contains a caption with length greater than 255 characters and is posted to the Phoenix API as a Reportback,  Gambit returns a 500 error with message: `Signup.postDraftReportbackSubmission error:API response is false.`

In Phoenix, the Reportback is saved without an Item. Phoenix logs show: `PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'caption' at row 1 in ...`

#### Desired Behavior
- The Reportback Item should be saved, with a truncated caption.

#### Why This Matters
- Missing Reportback images  🙅 
- Now that Blink will retry requests that return a 500 error, our Gambit error rate will skyrocket when we get errors like these.

#### Relevant Screenshots + Links
<img width="469" alt="screen shot 2017-05-02 at 9 45 31 am" src="https://cloud.githubusercontent.com/assets/1236811/25628719/200806a2-2f1c-11e7-98a2-2acf71c3696d.png">

**Comment by aaronschachter** [comment]
It's easy enough to make this check in Gambit... but I'd think the ideal place to fix it would be the Phoenix API to avoid it happening in other clients. Would this to be possible to replicate in Phoenix Next if a user disabled JS @DFurnes ?

**Comment by DFurnes** [comment]
It may make sense to wait and add this validation in Rogue, since we'll be flipping the switch on that soon-ish. We set up [some simple validation](https://github.com/DoSomething/phoenix-next/blob/879529f93097d80360bd288a8f226fa215528438/app/Http/Controllers/ReportbackController.php#L44) for this in Phoenix Next in the meantime.

**Comment by aaronschachter** [comment]
The Gambit 500 error can get triggered by submitting a huge `why_particpiated` as well:
```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'why_participated' at row 1 in /var/www/www.dosomething.org/releases/20170502211018/html/includes/database/database.inc:2227 Stack trace: #0 
```
Let's avoid by add a check in Gambit to truncate any string we're sending that's over 255 characters long as `caption` or `why_participated`.
