### ISSUE TITLE
multiword obscene words are not being flagged as inappropriate by the helpers function

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#895]
_BUG_
-------------------
#### Current Behavior
The `helpers.containsNaughtyWords('2girls 1 cup')` returns `false`.

Submitting a caption with this word does get accepted and stored in the database:
```
{
  "_id": ObjectId("secretobject"),
  "campaign": 2900,
  "user": "secretuser",
  "created_at": ISODate("2017-05-11T14:15:40.402Z"),
  "__v": 0,
  "quantity": 4,
  "photo": "https://s-media-cache-ak0.pinimg.com/236x/75/7f/1d/757f1d8c386e997a1c3f55b5b4059164.jpg",
  "caption": "2girls 1 cup is a bad video",
  "submitted_at": ISODate("2017-05-11T14:17:13.684Z")
}
```

#### Desired Behavior
The `helpers.containsNaughtyWords('2girls 1 cup')` should return `true` and should remove or reject this submission.

#### Steps to Replicate
call this function like I implemented it above.

#### Why This Matters
Some words that should be censored could get in the reportbacks

_FEATURE OVERVIEW_
-------------------
#### User Story
As an user, I should not be able to send a censored word as part of my reportback

_KEEP/KILL_
-------------------
**This function is no longer used in Gambit. We have to decide if we want to fix it or kill it.**

**Comment by aaronschachter** [comment]
I didn't remove this function in #877 -- but forgot to document the reasons for potentially keeping it in the codebase:

* We might want to use it reject out any messages we're sending to support. There's an ask from O'Doyle product team to avoid needing to read through profane messages

* invalidate reportback caption/why's. We don't do this on the web... but if we did, it could make sense to have a validator service somewhere (or use one that exists) to avoid duplicating the logic between apps.

**Comment by rapala61** [comment]
If we need to implement this feature, let's reopen and implement based on the desired behavior above. I'm going to close and remove the code for now as it's just taking space and can't be tested due to the bug explained here.
