### ISSUE TITLE
Error Occurred Message Type + Alerts

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#902]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a member of the O'Doyle Family, I want members who are stuck in Campaign Conversation to receive a message that an error occurred and that we're looking into it. I also want:
*  To be alerted (via Slack or email) that an Error Occurred message was sent (and the DS User / MC Profile ID it was sent to) 
* To let Blink know it shouldn't retry this error message 100 times because the request will fail every time if it's due to data issues (#901, #898, #881)
* To manage the copy for the Error Occurred as a new field on the Contentful Campaign content type, `ErrorOccurredMessage`.

#### Additional Information
We plan to send a custom header in the response to Blink to know whether to retry a response with status code 500, so we'll need a new Blink issue to check for it and retry accordingly once we're sending it through.

TODO:
* [ ] Add a `ErrorOccurredMessage` to the Contentful campaign type, and set a value for the default Campaign
* [ ] Identify scenarios where networking errors like #901, #898 will always return an error and then:
    * [ ] End the chatbot conversation with the Campaign's Error Occurred Message
    * [ ] Trigger an alert somehow and somewhere, like Stathat, Slack, Email, Blink, Twitter, smoke signal, etc 💭  
    * [ ] Include a new request header `x-blink-retry-suppress` with value set to `true` 

#### Why This Matters
Users used to receive a "Whoops, an error occurred message" via Mobile Commons, when our chatbot mData would post to Gambit and get an error back. 

Current behavior is that the user doesn't receive any message back at all, because Blink sends a success response to Mobile Commons indicating the message is queued. When Gambit responds with an error back to Blink, the user doesn't get a response back from us at all (and we wouldn't want them to receive 100 "An error occurred" messages for each Blink retry when the message is destined to fail).

**Comment by aaronschachter** [comment]
Blocked by https://github.com/DoSomething/blink/issues/71

**Comment by sergii-tkachenko** [comment]
@aaronschachter How about `x-blink-suppress-retry: true` instead?

**Comment by aaronschachter** [comment]
Sounds good, i'll update the description.

**Comment by sergii-tkachenko** [comment]
Actually, let's make it `x-blink-retry-suppress: true` to be more consistent with other `x-blink-retry-` headers.

**Comment by sergii-tkachenko** [comment]
Implemented in Blink in https://github.com/DoSomething/blink/pull/74.
