### ISSUE TITLE
Intermittent Phoenix POST Signups Internal Server Error

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#922]
_BUG_
-------------------
#### Current Behavior
- A handful of Users are triggering an Interval Server Error in Phoenix when Gambit posts to the Phoenix `/campaigns/:id/signup` endpoint. This may not be a bug in Gambit code, but I'm opening here as a place for investigation.

#### Desired Behavior
- Signup should have been successfully created.

#### Steps to Replicate
- Unknown

#### Instances
Here's an example in [Logstash](http://logs.dosomething.org/app/kibana#/doc/filebeat-*/filebeat-2017.06/nginx-access?id=AVyIjontKj9D4PJqrEia&_a=(filters:!((%27$$hashKey%27:%27object:1928%27,%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%27filebeat-*%27,key:application,negate:!f,value:phoenix),query:(match:(application:(query:phoenix,type:phrase))))),query:(query_string:(analyze_wildcard:!t,query:signup)),vis:(aggs:!((params:(field:application,orderBy:%272%27,size:20),schema:segment,type:terms),(id:%272%27,schema:metric,type:count)),type:histogram))&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))). @DFurnes mentioned these errors aren't showing up in Phoenix New Relic.

Here's an example Gambit request that fails on the POST Phoenix request:
```
2017-06-07T15:03:27.093573+00:00 app[web.3]: info: /v1/chatbot post:{"profile_id":"141768173","incoming_message":"Yes ","incoming_image_url":"","broadcast_id":"1279307","keyword":""}
2017-06-07T15:03:27.160616+00:00 app[web.3]: info: loaded broadcast:1279307 for user:59373b8aa0bfad134b7c2dd4
2017-06-07T15:03:27.458154+00:00 heroku[router]: at=info method=POST path="/v1/chatbot" host=ds-mdata-responder.herokuapp.com request_id=030463c0-f627-4456-99db-0dcadaac75e2 fwd="54.162.35.172" dyno=web.3 connect=8ms service=371ms status=500 bytes=300 protocol=http
2017-06-07T15:03:27.451827+00:00 app[web.3]: error: Signup.post error:Internal Server Error
```
* [User's Mobile Commons Profile](https://secure.mcommons.com/profiles/141768173)
* [User's Phoenix Profile](https://www.dosomething.org/us/user/712307) matching by mobile
* The broadcast ID, 1279307, points to campaign 1508, Thumb Wars (which is active and we're seeing plenty of other successful Signups for)

**Comment by aaronschachter** [comment]
@mirie and I were taking a look at [Phoenix Campaign Signup endpoint code](https://github.com/DoSomething/phoenix/blob/b6e57fa31712325dbb58bbd96f5b653afa098416/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L269) today, and noticed the `DOSOMETHING_SIGNUP_LOG_SIGNUPS` constant, which is set in the admin [DoSomething Signup config form](https://thor.dosomething.org/admin/config/dosomething/dosomething_signup). I've enabled in on Thor to inspect what it logs

DoSomething API module logs incoming Signup uid and source ([code](https://github.com/DoSomething/phoenix/blob/b6e57fa31712325dbb58bbd96f5b653afa098416/lib/modules/dosomething/dosomething_api/resources/campaign_resource.inc#L286))
* `_campaign_resource_signup values:{"source":"sms-mobilecommons","uid":1176550,"transactionals":true}`
* https://thor.dosomething.org/admin/reports/event/1775329

DoSomething Signup module logs saved Signup Entity ([code](97bea695eed6cd0ff58d796d94a886f3a0/lib/modules/dosomething/dosomething_signup/includes/SignupsController.php#L141))
* {"id":null,"nid":"2299","uid":1176550,"run_nid":"6441","source":"sms-mobilecommons","timestamp":1497306268,"transactionals":true,"sid":"3308100"}
* https://thor.dosomething.org/admin/reports/event/1775330

I think I added these `DOSOMETHING_SIGNUP_LOG_SIGNUPS` / `watchdog` calls back in the day because Drupal database errors don't log the id's used to trigger them (like in #907)

@DFurnes @blisteringherb  -- We could try enabling these logs in Phoenix, but I'm not sure if it will help surface whatever is causing the database error. But at this point, it seems worth it?  We haven't been successful finding any leads on the Gambit end. 🔍 

cc @rapala61

**Comment by DFurnes** [comment]
I think it's worth giving a try! 🕵️

**Comment by aaronschachter** [comment]
I've enabled the flag on [production](https://www.dosomething.org/admin/config/dosomething/dosomething_signup).

**Comment by aaronschachter** [comment]
Checking New Relic just now, and happened to find an instance of this error who has a Northstar Account without a Phoenix ID: http://aurora.dosomething.org/users/593f38a5a0bfad1c953ebcaf

This is their Mobile Commnons profile: https://secure.mcommons.com/profiles/230898695 -- it looks like they've only received one text from us, an external confirmation for Thumb Wars. They texted SHOWER and triggered this Internal Server Error.

Looking up this User by their mobile number in Phoenix shows more activity: https://www.dosomething.org/us/user/9265644
This particular user is an instance of the duplicate account bug (#901)
Looking up the user from the issue description and they too don't have a Phoenix ID: https://aurora.dosomething.org/users/59373b8aa0bfad134b7c2dd4, I must have missed the step of checking their Aurora profile when first investigating.

**Comment by aaronschachter** [comment]
Testing against Thor locally, I'm creating a new User with a bogus phone number and seeing these logs when trying to post a Signup:
```
ServicesException: Cannot create signup without a `northstar_id` or `uid`. in services_error()`. 
```
An example Thor Northstar ID is 5966abb710707d49445dba70.

**Comment by aaronschachter** [comment]
Spot checking another User who triggered a [Internal Server Error on POST Phoenix Campaign Signup:](https://rpm.newrelic.com/accounts/108038/applications/25522350/traced_errors/c837a4c7-71b9-11e7-bb42-0242ac11000b_0_1128?original_error_id=ebfbb76b-71b9-11e7-bb42-0242ac11000b_0_1128)

Mobile Commons profile: https://secure.mcommons.com/profiles/229043678
Aurora profile: https://aurora.dosomething.org/users/593bdcd7a0bfad7a143736c3 -- No Phoenix ID

**Comment by DFurnes** [comment]
If this is primarily an issue with missing `drupal_id` fields on Northstar profiles, it should be fairly uncommon for it to affect real people – there are just under 2,000 accounts with that problem.

One thing that'd help out would be switching to use `northstar_id` as [the provided ID](https://github.com/DoSomething/phoenix/pull/7480). Right now it does the exact same thing (we transform it to a UID within Drupal proxy), but as we refactor over the next week or two we can update it to just directly pass the Northstar ID to Rogue and sidestep any issues with `drupal_id` mismatches.

(Plus, this will make it easier to directly talk to Rogue in the future since it doesn't understand UIDs!)

**Comment by aaronschachter** [comment]
@DFurnes Let us know when it's ready and we'll make the change!

A related question -- Does Rogue have a POST signup endpoint available we could use instead?

**Comment by DFurnes** [comment]
It's ready to make the change now! After double-checking that nothing else is using it, we'll probably remove legacy Drupal `uid` support sometime in the next few weeks.

Regarding direct Rogue API access, I think we'll probably open that up once we have time to do a little more refactoring and testing over the next few weeks. But that's definitely the goal! 🔜

**Comment by aaronschachter** [comment]
Here's another User without a Phoenix ID that's triggering the 500 Internal Server Error when posting a Signup, from today's New Relic error report:

https://secure.mcommons.com/profiles/158111337 
https://aurora.dosomething.org/users/5875b15ca0bfad24bf02621d

**Comment by aaronschachter** [comment]
Another instance, from today's broadcast (1302278) --  https://aurora.dosomething.org/users/59139177a0bfad258915eaba

**Comment by aaronschachter** [comment]
Passing Northstar ID instead of Phoenix ID doesn't seem to have done the trick. Here's a User who received a 500 on Signup: http://aurora.dosomething.org/users/5938a315a0bfad5f9c3218d5

What's odd about this user is their Aurora account does not contain an email or a Phoenix ID. Their Mobile Commons Profile has a created date of 2013.

**Comment by DFurnes** [comment]
Hey Aaron! That makes sense – we haven't gotten a chance to refactor how this works in Phoenix yet, so it would still fail if a UID doesn't exist. Hopefully, we can fit that work into this or next sprint.

**Comment by aaronschachter** [comment]
Spotted random a Signups 500 error for [5845ca1fa0bfad4f3f3035d2](http://aurora.dosomething.org/users/5845ca1fa0bfad4f3f3035d2), who has a Phoenix ID [4358833](https://www.dosomething.org/us/user/4358833). They [have a few Signups](https://www.dosomething.org/api/v1/signups?user=4358833), but none found for the attempted Campaign (id 46)

**Comment by rapala61** [comment]
Another instance of an user without PhoenixId triggering 500 errors: https://aurora.dosomething.org/users/599a4fe4a0bfad4c6756350f

**Comment by aaronschachter** [comment]
I've created a test user, [59c2bff3a0bfad127629d789](http://aurora-thor.dosomething.org/users/59c2bff3a0bfad127629d789), who is triggering this every time I try to signup for a Campaign. Their Aurora profile shows they have a Phoenix account. In the Thor Phoenix-Ashes logs I see the error: 

> MESSAGE | ServicesException: Cannot create signup without a `northstar_id` or `uid`.
-- | --

But I also see the args passed, which do confirmed we're passing a `northstar_id`:
> _campaign_resource_access_alt args:["5411",{"source":"sms-mobilecommons","northstar_id":"59c2bff3a0bfad127629d789"}]

Searching Logstash for `ServicesException` for the past week does return results with the same `Cannot create signup` message...

**Comment by DFurnes** [comment]
I believe this is caused by a mismatch in Phoenix Thor & Northstar Thor database dumps - here's the corresponding user in Phoenix production: https://www.dosomething.org/us/user/9526396

**Comment by aaronschachter** [comment]
Ah, good call. 🕵️

**Comment by rapala61** [comment]
A lot of errors tonight. Users 59a07832a0bfad342a44de8a, 5876b000a0bfad4c7826b459, 59a35d7fa0bfad7d936b8e32, 5938a315a0bfad5f9c3218d5,  have no phoenix id and also triggering this `error: Signup.post error:Internal Server Error`. 

5892d5d8a0bfad2af129dee9 also triggered the error. I checked this user's state in Gambit Production and they weren't signed up even though they responded with `Y`. The odd thing is they have a phoenix id which doesn't fit the pattern. 🤔

**Comment by aaronschachter** [comment]
Looking into some of these with @DFurnes -- there's an internal lookup on the Phoenix side that checks for a Phoenix UID for a given Northstar ID. This could be why we see these even for users that have Aurora profiles with a Phoenix ID.

**Comment by aaronschachter** [comment]
We are posting Signups to Rogue directly now as of #974, which has just been deployed to production.

Next PR will post Reportbacks directly too, but posting Signups should no longer be an issue.
