### ISSUE TITLE
Stathat: gambit - campaignbot:menu_completed is no longer being tracked.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit#964]
_BUG_
-------------------
#### Current Behavior
- Stat `gambit - campaignbot:menu_completed` is no longer being tracked in Gambit.

#### Desired Behavior
- If we are going to continue keeping track of this, we should fix reporting of this stat.

#### Why This Matters
- Breaks the **Gambit reportback activity** reminder we check every morning.

**Comment by aaronschachter** [comment]
Our stats changed when we refactored the template names as `camelCase`. 

The Stathat card / Slack reminder message need to be updated to refer to https://www.stathat.com/v/stats/H7Od for `campaignbot:completedMenu`.

**Comment by aaronschachter** [comment]
Updated the Stathat card: https://www.stathat.com/cards/FoOK5awF6lx1
